### ISSUE TITLE
Error connecting to board

### ISSUE THREAD

**Issue by lubarb** [adafruit/Adafruit_CircuitPython_TLV493D#10]
From a Magtag, using:
```
import board
import busio
import adafruit_tlv493d

print("starting up")

# Hardware I2C setup:
i2c = busio.I2C(board.SCL, board.SDA)
tlv = adafruit_tlv493d.TLV493D(i2c)
```

I get an error when repeatedly connecting to the board (4366). 

If instead I change the i2c setup to use 
`i2c = busio.I2C(board.SCL, board.SDA, frequency = 400000)`
I can reconnect without trouble.

**Comment by caternuson** [comment]
What is the complete text of the error you are getting?

**Comment by lubarb** [comment]
Traceback (most recent call last):
  File "code.py", line 10, in <module>
  File "adafruit_tlv493d.py", line 81, in __init__
ValueError: No I2C device at address: 5e

That's with:
```
import board
import busio
import adafruit_tlv493d

print("starting up")

# Hardware I2C setup:
#i2c = busio.I2C(board.SCL, board.SDA, frequency = 400000)
i2c = busio.I2C(board.SCL, board.SDA)
tlv = adafruit_tlv493d.TLV493D(i2c)
```

so it's on the last line of code

**Comment by caternuson** [comment]
Can't easily reproduce this. I have your example above saved as `code.py` on the MagTag and have done a couple of soft resets without issue:
```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit MagTag with ESP32S2
>>>
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

code.py output:
starting up

Code done running.

Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit MagTag with ESP32S2
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

code.py output:
starting up

Code done running.

Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit MagTag with ESP32S2
>>>  
```

**Comment by lubarb** [comment]
Apparently there was something strange in my environment?

I erased my CIRCUITPY directory completely and reinstalled CircuitPython. I then added only the files and libraries I needed for the example, using adafruit-circuitpython-bundle-6.x-mpy-20210317. I'm no longer seeing the error.

I've started adding back some of the code I'd stripped out to isolate the problem still without the error. If I don't run into the error again in a couple of days, I'll close this issue. Or should I close it now and create a new one if necessary?

**Comment by dhalbert** [comment]
There is an unpleasant interaction between wifi and I2C on the ESP32-S2 which we think we have fixed. You might want to try the "Absolute Newest" download from circuitpython.org with your original code. Usually it causes `import wifi` to hang the board on import or similar, but you may be experiencing it in a different way. But it was unrelated to the frequency :/

**Comment by dhalbert** [comment]
Don't close this until you've done more testing. Fine to leave it open for now.

**Comment by lubarb** [comment]
The tlv board problem hasn't shown up again.

But after dealing with issue #9, I set a test running overnight and got an OSErrror in posting my result to mqtt. I changed things to run as fast as possible going to a dedicated raspberry pi mqtt broker, and seem to repeatably get an error within a few seconds.

Using Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit MagTag with ESP32S2.

Errors like:

```
Traceback (most recent call last):
  File "code.py", line 99, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 616, in publish
OSError: [Errno 11] EAGAIN

Traceback (most recent call last):
  File "code.py", line 99, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 614, in publish
OSError: [Errno 104] ECONNRESET

```
Posting this to adafruit_minimqtt.
