### ISSUE TITLE
Using 3 sensors

### ISSUE THREAD

**Issue by electronicDuck** [adafruit/Adafruit_CircuitPython_TLV493D#14]
Hi there,

Thank you for this library and all the work which has gone into it! I am new to this and I am trying to get 3 TLV sensors to work. I have connected them all to the same bus, they are connected as per the data sheet. Decoupling caps etc all provided, all running at 3.3v connected to a raspberry pi pico.
I can get 2 sensors to work well and react sensibly to a magnet but not 3. The attached code produces 3 readouts but TLV 2 readout is just noise. The magnet moving over sensor 2 provides a readout for TLV reading 3. I am pretty sure this is not a hardware issue in terms of hookup, but an addressing issue. I however cannot make it work.

Any help would be greatly appreciated,

Thank you

`
import time
import board
import busio
import digitalio
import adafruit_tlv493d

# Define i2c bus
i2c = busio.I2C(scl=board.GP1, sda=board.GP0)

# Sensor 1 VCC
en_pin = digitalio.DigitalInOut(board.GP2)
en_pin.switch_to_output()

# Sensor 2 VCC
en2_pin = digitalio.DigitalInOut(board.GP3)
en2_pin.switch_to_output()

# Sensor 3 VCC
en3_pin = digitalio.DigitalInOut(board.GP4)
en3_pin.switch_to_output()

# Power down sensors to start addressing sequence
en_pin.value = False
en2_pin.value = False
en3_pin.value = False
time.sleep(0.2)

# Enable and configure sensor 1
en_pin.value = True
tlv = adafruit_tlv493d.TLV493D(i2c, addr_reg=1)
tlv = adafruit_tlv493d.TLV493D(i2c, address=0x5a, addr_reg=1)

# Enable and configure sensor 2
en2_pin.value = True
tlv2 = adafruit_tlv493d.TLV493D(i2c, addr_reg=3)
tlv2 = adafruit_tlv493d.TLV493D(i2c, address=0x4a, addr_reg=3)

# Enable and configure sensor 3
en3_pin.value = True
tlv3 = adafruit_tlv493d.TLV493D(i2c, addr_reg=0)
tlv3 = adafruit_tlv493d.TLV493D(i2c, address=0x5e, addr_reg=0)

while True:
    print("Values")
    print("X1: %s, Y1: %s, Z1: %s mT" % tlv.magnetic)
    print("X2: %s, Y2: %s, Z2: %s mT" % tlv2.magnetic)
    print("X3: %s, Y3: %s, Z3: %s mT" % tlv2.magnetic)
    time.sleep(1)
`

**Comment by ladyada** [comment]
the third line is still reading from tlv2?

**Comment by electronicDuck** [comment]
Ah so it is! Thank you! I have been staring at this all week trying to make it work! Sorry!

**Comment by ladyada** [comment]
nice :)
