### ISSUE TITLE
TLV493D supports two different I2C addresses but library doesn't

### ISSUE THREAD

**Issue by blepblorp** [adafruit/Adafruit_CircuitPython_TLV493D#5]
The TLV493D can be configured to have I2C address 5E or 1F, but the library only supports address 5E. See section 6 of the manual for details: https://www.infineon.com/dgdl/Infineon-TLV493D-A1B6_3DMagnetic-UM-v01_03-EN.pdf?fileId=5546d46261d5e6820161e75721903ddd#G5.10752908

**Comment by ladyada** [comment]
hi, if you can submit a PR to add an `address` kwarg, we'll take a look!
https://github.com/adafruit/Adafruit_CircuitPython_TLV493D/blob/master/adafruit_tlv493d.py#L92
